enum ClientResponseType
{
    UpdateTheme,
    UpdateOsuId,
    UpdateLocale,
    UpdatePreferedGame,
    UpdateWaifuDB,
    UpdateItemDB,
    UpdateSetDB,
    StartFight,
    ClaimFight,
    ClaimDungeonFight,
    GetSession,
    AddBeatmap,
    ConnectWithDiscord,
    GetPullResults,
    GetMapData,
    VerifyOsuId,
    VerifyMaimaiToken,
    StartDungeon,
    StopDungeon,
    EquipItem,
    UnequipItem,
    Logout,
    GetLevelRewards,
    GetLevelRewardsData,
    SendWaifuToActivity,
    UseUserConsumable,
    CheckContinuousFight,
    UpgradeEquipment,
    UpdateUserWaifu,
    UpdateUserInventory,
    BecomeAdmin,
    ClaimActivity,
    CancelActivity,
}

export default ClientResponseType