enum ServerResponseType
{
    ProvideUser,
    ProvideMapData,
    ProvideFightResults,
    ProvidePullResults,
    Notification,
    ProvideSession,
    ProvideBanners,
    ProvideDungeons,
    ProvideResearchNodes,
    ProvideCraftingRecipes,
    ProvideLoot,
    ProvideAndGiveLoot,
    ProvideWaifuDB,
    ProvideSetDB,
    ProvideEquipmentDB,
    ProvideItemDB,
    ProvideMaimaiChartData,
    ProvideLevelRewardsData,
    ProvideActiveDungeon,
    OsuIdUpdateSuccess,
    MaimaiTokenUpdateSuccess,
    ProvideContinuousFightResults,
    ConfirmEquip,
    ConfirmUnequip,
    ConfirmActivity,
    ConfirmCancelActivity,
    ConfirmActivityClaim,
    ConfirmDungeonStarted,
    FreeWaifus,
}

export default ServerResponseType