public class OsuBeatmap {
    public int beatmapset_id;
    public float difficulty_rating;
    public long id;
    public string mode;
    public string status;
    public int total_length;
    public int user_id;
    public string version;
    public float accuracy;
    public float ar;
    public float bpm;
    public float cs;
    public float drain;
    public bool convert;
    public int count_circles;
    public int count_sliders;
    public int count_spinners;
    public string deleted_at;
    public int hit_length;
    public bool is_scoreable;
    public string last_updated;
    public int mode_int;
    public int passcount;
    public int playcount;
    public int ranked;
    public string url;
    public string checksum;
}