public class Config {
        public required string default_locale;
        public required string dungeon_storage_path;
        public required string database_path;
        public required uint automatic_backup_interval_in_seconds;
        public required string automatic_backup_database_storage_path;
        public required string automatic_backup_database_storage_path2;
        public required string osu_tokens_storage_path;
        public required string osu_chat_tokens_storage_path;
        public required string banners_storage_path;
        public required string discord_api_url;
        public required string osu_api_url;
        public required string ws_prod_server_url;
        public required int ws_port;
        public required string ws_dev_server_url;
        public required string base_url;
        public required bool dev;
        public required string maitea_api_url;
        public required string discord_avatar_url;
        public required string osu_oauth_url;
        public required string chat_osu_oauth_url;
        public required string[] available_languages;
}